###
GET http://localhost:8080/customer/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
GET http://localhost:8080/customer/allbookings/1
Authorization: 532552db908e5002da1058329fa95554

###
POST http://localhost:8080/customer/add/Customer4/1971-06-11/44/New_Road/Newton/NE45TY

###
GET http://localhost:8080/room/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
GET http://localhost:8080/roomtype/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
POST http://localhost:8080/roomtype/add/SUITE
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
DELETE http://localhost:8080/roomtype/delete/3
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
POST http://localhost:8080/roomtype/update/3/BEING_REPAIRED
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
GET http://localhost:8080/booking/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
POST http://localhost:8080/booking/add/1/2023-07-04/2023-07-11/1
Authorization: 532552db908e5002da1058329fa95554

###
DELETE http://localhost:8080/booking/delete/1/3
Authorization: 532552db908e5002da1058329fa95554

###
POST http://localhost:8080/booking/update/1/1/2024-06-11/2024-06-16
Authorization: 532552db908e5002da1058329fa95554

###
POST http://localhost:8080/customer/checkcredentials/Customer1/1951-04-13

###
POST http://localhost:8080/customer/logout/1
Authorization: 532552db908e5002da1058329fa95554

###
POST http://localhost:8080/staff/checkcredentials/staff2@hotel.com/hotelstaff2

###
POST http://localhost:8080/staff/logout/2
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb
