### STAFF
GET http://localhost:8080/customer/all
Authorization: 447c0806291fae1bca1f7d27fdb57867

### CUSTOMER
GET http://localhost:8080/customer/allbookings/1
Authorization: 4caf0763a762d4557e166621c73f6576

###
POST http://localhost:8080/customer/add/Customer5/1971-06-11/44/New_Road/Newton/NE45TY

### STAFF
GET http://localhost:8080/room/all
Authorization: 447c0806291fae1bca1f7d27fdb57867

### STAFF
GET http://localhost:8080/roomtype/all
Authorization: 447c0806291fae1bca1f7d27fdb57867

### STAFF
POST http://localhost:8080/roomtype/add/SUITE
Authorization: 447c0806291fae1bca1f7d27fdb57867

### STAFF
DELETE http://localhost:8080/roomtype/delete/3
Authorization: 447c0806291fae1bca1f7d27fdb57867

### STAFF
POST http://localhost:8080/roomtype/update/3/BEING_REPAIRED
Authorization: 447c0806291fae1bca1f7d27fdb57867

### STAFF
GET http://localhost:8080/booking/all
Authorization: 447c0806291fae1bca1f7d27fdb57867

### CUSTOMER
POST http://localhost:8080/booking/add/1/2023-07-04/2023-07-11/1
Authorization: 4caf0763a762d4557e166621c73f6576

### CUSTOMER
DELETE http://localhost:8080/booking/delete/1/3
Authorization: 4caf0763a762d4557e166621c73f6576

### CUSTOMER
POST http://localhost:8080/booking/update/1/1/2024-06-11/2024-06-16
Authorization: 4caf0763a762d4557e166621c73f6576

###
POST http://localhost:8080/customer/checkcredentials/Customer1/1951-04-13

### CUSTOMER
POST http://localhost:8080/customer/logout/1
Authorization: 4caf0763a762d4557e166621c73f6576

###
POST http://localhost:8080/staff/checkcredentials/staff2@hotel.com/hotelstaff2

### STAFF
POST http://localhost:8080/staff/logout/2
Authorization: 447c0806291fae1bca1f7d27fdb57867
