###
GET http://localhost:8080/customer/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
GET http://localhost:8080/customer/allbookings/2

###
POST http://localhost:8080/customer/add/=Customer4/=1971-06-11/=44/=New_Road/=Newton/=NE45TY

###
GET http://localhost:8080/room/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
GET http://localhost:8080/roomtype/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
POST http://localhost:8080/roomtype/add/=SUITE

###
DELETE http://localhost:8080/roomtype/delete/3

###
POST http://localhost:8080/roomtype/update/3/=BEING_REPAIRED

###
GET http://localhost:8080/booking/all
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb

###
POST http://localhost:8080/booking/add/1/2023-07-04/2023-07-11/1
Authorization: -76fdbfb1b2b6c82390298fc56e04e7bf

###
DELETE http://localhost:8080/booking/delete/=3

###
POST http://localhost:8080/booking/update/=1/2023-06-11/2023-06-16

###
POST http://localhost:8080/customer/checkcredentials/Customer1/1951-04-13

###
POST http://localhost:8080/customer/logout/1
Authorization: -76fdbfb1b2b6c82390298fc56e04e7bf

###
POST http://localhost:8080/staff/checkcredentials/staff2@hotel.com/hotelstaff2

###
POST http://localhost:8080/staff/logout/2
Authorization: 7e7aed3da48fd59f1c06a748b5ec2dfb
